# Generated by Django 2.0.4 on 2018-05-29 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=120, null=True)),
                ('date', models.CharField(blank=True, max_length=120, null=True)),
                ('num_pages', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'permissions': (('file_access', 'Can access this file'),),
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('alternatives', models.ManyToManyField(blank=True, related_name='_keyword_alternatives_+', to='main.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('page_name', models.CharField(blank=True, max_length=120, null=True)),
                ('previous_match', models.BooleanField(default=False)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_on', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=140, null=True)),
                ('units', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File')),
            ],
        ),
        migrations.CreateModel(
            name='ResultKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Keyword')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Result')),
            ],
        ),
        migrations.CreateModel(
            name='SearchSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_of_origin', models.FilePathField(max_length=255, path='\\\\UKVIR05011\\ukvfmsecroot\\P\\Project Dynamics\\Engagements\\2_Project Data\\03 Dev folder\\05 RESOURCES\\Searches')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('first_page', models.IntegerField()),
                ('last_page', models.IntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File')),
            ],
        ),
        migrations.CreateModel(
            name='StoredSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140, unique=True)),
                ('search_type', models.CharField(max_length=30)),
                ('sub_type', models.CharField(max_length=30)),
                ('keywords', models.ManyToManyField(blank=True, to='main.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='TimestampGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('timestamp', models.CharField(max_length=25)),
                ('default_timestamp', models.CharField(max_length=25)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File')),
            ],
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('default_unit', models.CharField(max_length=25)),
                ('unit', models.CharField(max_length=25)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.File')),
            ],
        ),
        migrations.AddField(
            model_name='searchset',
            name='searches',
            field=models.ManyToManyField(blank=True, to='main.StoredSearch'),
        ),
        migrations.AddField(
            model_name='result',
            name='keyword',
            field=models.ManyToManyField(blank=True, through='main.ResultKeyword', to='main.Keyword'),
        ),
        migrations.AddField(
            model_name='result',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Page'),
        ),
        migrations.AddField(
            model_name='result',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StoredSearch', to_field='description'),
        ),
        migrations.AddField(
            model_name='result',
            name='timestamp_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TimestampGroup'),
        ),
        migrations.AddField(
            model_name='result',
            name='unit_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UnitGroup'),
        ),
        migrations.AddField(
            model_name='page',
            name='section',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Section'),
        ),
    ]
