# Generated by Django 2.0.4 on 2018-07-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180703_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='units',
            new_name='unit',
        ),
    ]
