# Generated by Django 2.0.6 on 2018-10-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180706_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='SapData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_partner', models.CharField(blank=True, max_length=255, null=True)),
                ('master_profit_centre', models.CharField(blank=True, max_length=255, null=True)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('project_customer_no', models.CharField(blank=True, max_length=255, null=True)),
                ('project_customer', models.CharField(blank=True, max_length=255, null=True)),
                ('g_m_uhc', models.CharField(blank=True, max_length=255, null=True)),
                ('cust_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('g_m_pe', models.CharField(blank=True, max_length=255, null=True)),
                ('g_m_uhc_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('g_m_uhc_subindustry', models.CharField(blank=True, max_length=255, null=True)),
                ('sector', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_type', models.CharField(blank=True, max_length=255, null=True)),
                ('slc_code', models.CharField(blank=True, max_length=255, null=True)),
                ('g_m_uhc_segmt', models.CharField(blank=True, max_length=255, null=True)),
                ('uhc', models.CharField(blank=True, max_length=255, null=True)),
                ('uhc_number', models.CharField(blank=True, max_length=255, null=True)),
                ('gross_revenue', models.CharField(blank=True, max_length=255, null=True)),
                ('provisions', models.CharField(blank=True, max_length=255, null=True)),
                ('net_services', models.CharField(blank=True, max_length=255, null=True)),
                ('product_sales', models.CharField(blank=True, max_length=255, null=True)),
                ('other_revenue', models.CharField(blank=True, max_length=255, null=True)),
                ('net_revenue', models.CharField(blank=True, max_length=255, null=True)),
                ('rrr', models.CharField(blank=True, max_length=255, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='notes',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
