# Generated by Django 2.0.6 on 2018-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_result_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='version',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
