# Generated by Django 2.0.6 on 2018-11-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20181012_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampgroup',
            name='default_timestamp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='timestampgroup',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unitgroup',
            name='default_unit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='unitgroup',
            name='unit',
            field=models.CharField(max_length=255),
        ),
    ]
