# Generated by Django 2.0.6 on 2018-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181120_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedsearch',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
    ]
