# Generated by Django 2.0.6 on 2018-11-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_storedsearch_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='new_flag',
        ),
        migrations.AlterField(
            model_name='searchset',
            name='file_of_origin',
            field=models.FilePathField(max_length=255, path='C:\\Users\\whunkin\\Documents\\Dynamics_Test\\Searches'),
        ),
    ]
