# Generated by Django 2.0.6 on 2018-11-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181129_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchset',
            name='file_of_origin',
            field=models.FilePathField(max_length=255, path='\\\\UKVIR05011\\ukvfmsecroot\\P\\Project Dynamics\\Engagements\\2_Project Data\\03 Dev folder\\05 RESOURCES\\Searches'),
        ),
    ]
