# Generated by Django 2.0.6 on 2018-11-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181129_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedsearch',
            old_name='order_id',
            new_name='del_id',
        ),
    ]
