# Generated by Django 2.0.4 on 2019-01-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181130_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
