# Generated by Django 2.0.4 on 2019-02-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190204_0601'),
    ]

    operations = [

        migrations.AddField(
            model_name='result',
            name='searchset_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='storedsearch_id',
            field=models.IntegerField(null=True),
        ),
    ]
