# Generated by Django 2.0.4 on 2019-02-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190207_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),

    ]
