# Generated by Django 2.0.4 on 2019-11-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_result_sector'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='file',
        #     name='opration_country',
        #     field=models.CharField(default='United Kingdom', max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='file',
        #     name='source_country',
        #     field=models.CharField(default='United Kingdom', max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='searchset',
        #     name='file_of_origin',
        #     field=models.FilePathField(max_length=255, path='\\\\uk.deloitte.com\\ukvfmsecroot\\P\\Project Dynamics\\Engagements\\2_Project Data\\03 Dev folder\\05 RESOURCES\\Searches'),
        # ),
    ]
