# Generated by Django 2.0.4 on 2020-10-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20191104_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(default='', max_length=100)),
                ('English_short_name', models.CharField(default='', max_length=100)),
                ('Alpha_3_code', models.CharField(default='', max_length=100)),
                ('Time_Entry_System', models.CharField(default='', max_length=100)),
                ('Swift_Charge_Code', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
