# Generated by Django 2.0.4 on 2020-12-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_country'),
    ]

    operations = [

        migrations.AddField(
            model_name='result',
            name='auto_added_flag',
            field=models.BooleanField(default=False),
        ),

    ]
